TRANSACTION_TYPE_DEPOSIT = 'deposit'
TRANSACTION_TYPE_WITHDRAW = 'withdraw'
TRANSACTION_TYPE_TRANSFER = 'transfer'

TRANSACTION_TYPES = (
    (TRANSACTION_TYPE_DEPOSIT, 'Deposit'),
    (TRANSACTION_TYPE_WITHDRAW, 'Withdraw'),
    (TRANSACTION_TYPE_TRANSFER, 'Transfer'),
)

TRANSACTION_STATUS_PENDING = 'pending'
TRANSACTION_STATUS_COMPLETED = 'completed'
TRANSACTION_STATUS_FAILED = 'failed'

TRANSACTION_STATUSES = (
    (TRANSACTION_STATUS_PENDING, 'Pending'),
    (TRANSACTION_STATUS_COMPLETED, 'Completed'),
    (TRANSACTION_STATUS_FAILED, 'Failed'),
)
